const state = {
    num:0,
    editType:-1,//-1是默认值，0代表新建病历，1代表修改病历
    navHeight:43,//代表顶部tab栏的高度
    CaseId:-1,//代表本次病历id
    templateId:-1,//代表本次病历使用的模板
    pageIndex:-1,//代表路由页面的索引值，初始为基本信息-1，
    subIndex:-1,
    teamList:[],
    tabList:[],//顶部动态tab栏数据
    changePageOnOff:false,//当他改变为false的时候说明那个页面有错误
    clickNum:0,
    teamId:-1,
    baseInfo:{
        'patientName':'',
        'ageYear':'',
        'ageMonth':'',
        'ageDay':'',
        'sex':'',
        'phoneNum':'',
        'admissionNum':'',
        'affiliation':'',
        'affiliationTeamName':''
    },
    subPageData:[],
    pageInfo:{
      pageId:'',
      pageName:'',
      pageData:Object
    },
    chiefComplaintInfo:{
        illPlace:'',
        illSymptoms:'',
        widthIllSymptoms:'',
        illDurationTime:''
    },
    'titleName':'填写患者基本信息'//header栏的名字动态改变
};
export default state;
